# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8fbcd7c6b227592a88b708ae18f47f1bcf313a9052aa436a016c96d639cd09ff39ad029fa3937bc732c3e954927cace379a36a9d124c75957d92425424c9889

test:
  secret_key_base: 40ec8b2e0efd67f502b7a826b6a45e6fbd555602929148cb297d8f605814321fcae3a7d647a022b1a1a276a5b7cd79b7a00a5ea58737e0b32a6760ba40283b0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
